dl/urls.py
from django.urls import path
from . import views

app_name = "dl"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.check_account, name='check_account'),
    path('grades/', views.grades, name='grades'),
    path('grades/<int:course_id>', views.grades_detail, name='grades_detail'),
    path('course/course_id=<int:courses_id>', views.courses, name='courses'),
    path('course/course_id=<int:courses_id>/add_task', views.add_task_menu, name='add_task_menu'),
    path('course/course_id=<int:courses_id>/add_task/task_id=<int:task_id>', views.add_task_student, name='add_task_student'),
    path('course/course_id=<int:courses_id>/add_task/add', views.add_task, name='add_task'),
    path('course/course_id=<int:courses_id>/task_id=<int:task_id>', views.show_task, name='show_task'),
    path('course/course_id=<int:courses_id>/<int:author_id>', views.upload_file, name='upload_file'),
    path('course/course_id=<int:courses_id>/attendance', views.for_attendance, name='for_attendance'),
    path('course/course_id=<int:course_id>/rate/group_id=<int:group_id>/task_id=<int:task_id>', views.rate, name='rate'),
    path('rate/<int:course_id>/<int:group_id>/<int:teacher_id>/<int:student_id>/<int:task_id>', views.set_grade, name='set_grade'),
    path('course/search', views.search_course, name='search_course'),
    path('profile/<int:user_id>', views.see_profile, name='see_profile'),
    path('profile/<int:user_id>/change_photo', views.change_photo, name='change_photo')
    #path('courses/', views.teacher_courses, name='courses')
    #path('groups/', views.all_groups, name='all_groups'),
    #path('group_id=<int:group_id>', views.index, name='index'),
    #path('student_id=<int:student_id>', views.show_subjects, name='show_subjects'),
    #path('<int:student_id>/<int:subject_id>/', views.get_grade, name='get_grade'),
]

dliteproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dl.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dl/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField


class Courses(models.Model):
    class Meta:
        db_table = "courses"

    subject_name        = models.CharField(max_length=200)

    def __str__(self):
        id = str(self.pk)
        return self.subject_name + " | " + id


class Teacher(models.Model):
    class Meta:
        db_table = "teachers"
    user                = models.OneToOneField(User, on_delete=models.CASCADE)
    courses             = models.ManyToManyField(Courses)
    image = models.ImageField(upload_to='profiles_images', blank=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " | " + self.user.username


class Department(models.Model):
    class Meta:
        db_table = "departments"
    department_name     = models.CharField(max_length=80)
    courses             = models.ManyToManyField(Courses)

    def __str__(self):
        return self.department_name


class Groups(models.Model):
    class Meta:
        db_table = "groups"
    group_dep           = models.ForeignKey(Department, on_delete=models.CASCADE)
    group_name          = models.CharField(max_length=50)

    def __str__(self):
        return self.group_name


class Student(models.Model):
    class Meta:
        db_table = "students"
    user                = models.OneToOneField(User, on_delete=models.CASCADE)
    group               = models.ForeignKey(Groups, on_delete=models.CASCADE)
    image               = models.ImageField(upload_to='profiles_images', blank=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " | " + self.user.username


class Grades(models.Model):
    class Meta:
        db_table = "grades"

    student             = models.ForeignKey(Student, on_delete=models.CASCADE)
    teacher             = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    course              = models.ForeignKey(Courses, on_delete=models.CASCADE)
    group               = models.ForeignKey(Groups, on_delete=models.CASCADE)
    date                = models.DateTimeField(auto_now_add=True)
    grade               = models.IntegerField(default=0)

    def __str__(self):
        return self.student.user.first_name + " " + self.student.user.last_name + " | " + self.course.subject_name


class Files(models.Model):
    class Meta:
        db_table = 'files'

    course              = models.ForeignKey(Courses, on_delete=models.CASCADE)
    title               = models.CharField(max_length=150)
    author              = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    file                = models.FileField(upload_to='files', blank=True)
    date                = models.DateTimeField(auto_now_add=True)
    week                = models.IntegerField()

    def __str__(self):
        return self.title


class Task(models.Model):
    class Meta:
        db_table = 'tasks'

    course              = models.ForeignKey(Courses, on_delete=models.CASCADE)
    title               = models.CharField(max_length=150)
    info                = models.TextField(max_length=300)
    file                = models.FileField(upload_to='files/tasks', blank=True)
    week                = models.IntegerField()
    date1               = models.DateTimeField()
    date2               = models.DateTimeField()
    groups              = models.ManyToManyField(Groups)

    def __str__(self):
        return self.course.subject_name + " | " + self.title


class StudProc(models.Model):
    class Meta:
        db_table = 'studproc'

    course              = models.ForeignKey(Courses, on_delete=models.CASCADE)
    date_start          = models.DateTimeField()
    date_end            = models.DateTimeField()
    CHOICES = (
        ('PRACTICE', 'PRACTICE'),
        ('LECTURE', 'LECTURE')
    )
    type                = MultiSelectField(choices=CHOICES)
    room                = models.IntegerField()
    group               = models.ForeignKey(Groups, on_delete=models.CASCADE)
    teacher             = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.course.subject_name + " | " + str(self.room)


class GradesForTask(models.Model):
    class Meta:
        db_table = "task_grades"

    task                = models.ForeignKey(Task, on_delete=models.CASCADE)
    teacher             = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    student             = models.ForeignKey(Student, on_delete=models.CASCADE)
    group               = models.ForeignKey(Groups, on_delete=models.CASCADE)
    course              = models.ForeignKey(Courses, on_delete=models.CASCADE)
    date                = models.DateTimeField(auto_now_add=True)
    grade               = models.IntegerField(default=0)

    def __str__(self):
        return self.course.subject_name + " | " + self.task.title


class StudentFilesForTask(models.Model):
    class Meta:
        db_table = "students_files"

    student             = models.ForeignKey(Student,on_delete=models.CASCADE)
    task                = models.ForeignKey(Task, on_delete=models.CASCADE)
    date                = models.DateTimeField(auto_now_add=True)
    file                = models.FileField(upload_to='files/student', blank=True)

    def __str__(self):
        return self.student.user.first_name + " " + self.student.user.last_name + " | " + self.task.title

dl/forms.py
from django import forms
from .models import Files

class DLFiles(forms.ModelForm):
    class Meta:
        model = Files
        fields = {'course','week','file','title','author','date'}

dl/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.contrib import auth
from django.urls import reverse
from django.core.mail import send_mail
from .models import Student, Groups, Grades, Teacher, Department, Courses, StudProc, Files, Task, GradesForTask, StudentFilesForTask
import datetime
from django.utils import timezone
from django.core.files.storage import FileSystemStorage


def home(request):
    teachers_list = {}
    kek = {}
    kek.update(csrf(request))
    tasks = ""
    if request.user.is_authenticated:
        try:
            if request.user.teacher:
                courses_list = Courses.objects.all().filter(teacher=request.user.teacher.pk).order_by('subject_name')

            else:
                return redirect('/')

        except Teacher.DoesNotExist:
            if request.user.student:
                courses_list = Courses.objects.all().filter(department=request.user.student.group.group_dep).order_by('subject_name')
                teachers_list = Teacher.objects.all()
                tasks = Task.objects.all().filter(groups=request.user.student.group).order_by('date2')
            else:
                return redirect('/')
        kek = {
            'teachers_list': teachers_list,
            'courses_list': courses_list,
            'user': auth.get_user(request),
            'tasks': tasks
        }
    return render(request, 'main.html', kek)


def check_account(request):
    args = {}
    args.update(csrf(request))

    if not request.user.is_authenticated:
        if request.POST:
            login = request.POST['enter_login']
            password = request.POST['enter_pass']
            user = auth.authenticate(username=login, password=password)

            if user is not None:
                auth.login(request, user)
                return redirect('/')
            else:
                args['login_error'] = "Login or password is incorrect!"
                return render(request, 'login.html', args)
        else:
            return render(request, 'login.html', args)
    else:
        auth.logout(request)
        return redirect('/')


def grades(request):
    courses_list = Courses.objects.all().filter(department=request.user.student.group.group_dep).order_by('subject_name')
    grades_list = Grades.objects.all().filter(student__user__username=request.user.username).order_by('-date')

    kek = {
        'grades_list': grades_list,
        'courses_list': courses_list,
        'student': auth.get_user(request)
    }

    return render(request, 'grades.html', kek)


def grades_detail(request, course_id):
    tasks_list = Task.objects.all().filter(course_id=course_id).order_by('title')

    try:
        grade = GradesForTask.objects.all().filter(course_id=course_id, student_id=request.user.student.pk).order_by('-date')
    except:
        grade = 0

    course_id = course_id
    course_name = Courses.objects.filter(pk=course_id).get().subject_name
    kek = {
        'grades_list': grade,
        'tasks_list': tasks_list,
        'student': auth.get_user(request),
        'course_id': course_id,
        'course_name': course_name
    }

    return render(request, 'gradedetail.html', kek)



def courses(request, courses_id):
    context = {}
    group_id = ""
    if request.method == "POST":
        uploaded_file = request.FILES['file']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)

    groups_list = Groups.objects.all().filter(group_dep__courses=courses_id)
    files_list = Files.objects.all().filter(course_id=courses_id)
    tasks_list = Task.objects.all().filter(course_id=courses_id)
    timenow = timezone.now()
    weeks = []
    for i in range(1,16):
        weeks.append(i)

    try:
        course_name = Courses.objects.get(pk=courses_id).subject_name
    except:
        raise Http404("Course not found!")

    kek = {
        'group_id': group_id,
        'date': timenow,
        'tasks_list': tasks_list,
        'files_list': files_list,
        'course_name': course_name,
        'weeks': weeks,
        'groups_list': groups_list,
        'course_id': courses_id,
        'context': context,
    }

    return render(request, 'course.html', kek)


def see_profile(request, user_id):
    s_user = " "
    t_user = " "
    courses_list = []

    try:
        if request.user.teacher:
            if Student.objects.filter(user_id=user_id).exists():
                s_user = Student.objects.get(user_id=user_id).user
                courses_list = Courses.objects.all().filter(department=s_user.student.group.group_dep).order_by('subject_name')
        else:
            return redirect('/')

    except:
        if request.user.student:
            if Teacher.objects.filter(user_id=user_id).exists():
                t_user = Teacher.objects.get(user_id=user_id).user
                courses_list = Courses.objects.all().filter(teacher__user_id=user_id).order_by('subject_name')
        else:
            return redirect('/')
    kek = {
        'student': s_user,
        'teacher': t_user,
        'courses_list': courses_list
    }
    return render(request, 'profile.html', kek)


def change_photo(request, user_id):
    try:
        if request.user.student:
            user = Student.objects.get(user_id=user_id)
            user.image = request.FILES['file']
            user.save()

    except:
        if request.user.teacher:
            user = Teacher.objects.get(user_id=user_id)
            user.image = request.FILES['file']
            user.save()

    return HttpResponseRedirect(reverse('dl:see_profile', args=(user_id,)))

def rate(request, course_id, group_id, task_id):
    grades_list = GradesForTask.objects.all().filter(course_id=course_id, task_id=task_id).order_by('-date')
    students_list = Student.objects.all().filter(group_id=group_id)
    group_name = Groups.objects.get(pk=group_id).group_name
    task = Task.objects.get(pk=task_id)
    course_id = course_id
    course_name = Courses.objects.get(pk=course_id).subject_name
    files_list = StudentFilesForTask.objects.filter(student__group=group_id)
    kek = {
        'grades_list': grades_list,
        'students_list': students_list,
        'course_id': course_id,
        'group_name': group_name,
        'course_name': course_name,
        'task': task,
        'files_list': files_list
    }
    return render(request, 'rate.html', kek)


def set_grade(request, course_id, group_id, teacher_id, student_id, task_id):
    message = ''
    if request.method == 'POST':
        course = Courses.objects.get(pk=course_id)
        group = Groups.objects.get(pk=group_id)
        teacher = Teacher.objects.get(user_id=teacher_id)
        student = Student.objects.get(pk=student_id)
        task = Task.objects.get(pk=task_id)
        newGrade = int(request.POST['inputGrade'])
        #email = student.user.email
        try:
            grade = GradesForTask.objects.get(course_id=course_id, group_id=group_id, teacher_id=teacher_id, student_id=student_id,task_id=task_id)
            grade.grade = newGrade
            grade.save()

            message = 'You take ' + str(newGrade) +'!/n'+ 'Course: ' + course.subject_name + './n' + 'Task title: ' + task.title
            send_mail('DLite | You have rated!', message, 'theswtrwthr@gmail.com', ['said.ur@mail.ru'], fail_silently=False)
        except:
            grade = GradesForTask()
            grade.course = course
            grade.group = group
            grade.student = student
            grade.teacher = teacher
            grade.grade = newGrade
            grade.task = task
            grade.save()
            message = 'You take ' + str(
                newGrade) + '!/n' + 'Course: ' + course.subject_name + './n' + 'Task title: ' + task.title
            send_mail('DLite | You have rated!', message, 'theswtrwthr@gmail.com', ['said.ur@mail.ru'],
                      fail_silently=False)

    else:
        raise Http404("wdadw not found!")

    return HttpResponseRedirect(reverse('dl:rate', args=(course_id, group_id,task_id)))


def search_course(request):
    if request.method == "POST":
        try:
            courses_list = Courses.objects.all().filter(subject_name__contains=request.POST['name'], teacher=request.user.teacher).order_by('subject_name')
            course_size = len(courses_list)
        except:
            courses_list = Courses.objects.all().filter(subject_name__contains=request.POST['name'],department=request.user.student.group.group_dep ).order_by('subject_name')
            course_size = len(courses_list)
    else:
        raise Http404("error not found!")

    return render(request, 'main.html',
                  {'courses_list': courses_list,
                   'course_size': course_size})

def for_attendance(request, courses_id):
    studproc = StudProc.objects.filter(course_id=courses_id)
    course_name = Courses.objects.get(pk = courses_id)
    kek = {
        'studproc': studproc,
        'course_name': course_name,
        'course_id': courses_id
    }

    return render(request, 'attendance.html', kek)


def upload_file(request,courses_id,author_id):
    title = request.POST['title']
    uploaded_file = request.FILES['file']
    new_author_id = Teacher.objects.get(pk=author_id)
    new_course_id = Courses.objects.get(pk=courses_id)
    week = request.POST['week']
    files = Files()
    files.file = uploaded_file
    files.author = new_author_id
    files.week = week
    files.title = title
    files.course = new_course_id
    files.save()


    return HttpResponseRedirect(reverse('dl:courses', args=(courses_id,)))


def add_task_menu(request, courses_id):
    groups = Groups.objects.filter(group_dep__courses=courses_id)
    course_name = Courses.objects.get(pk=courses_id).subject_name
    course_id = courses_id

dl/templates/course.html
{% extends 'main.html' %}
{% load staticfiles %}
{% load cmds %}
{% block title %}Course: {{ course_name }}{% endblock %}
{% block navigation %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'dl:home' %}">Home</a></li>
    <li class="breadcrumb-item" aria-current="page">{{ course_name }}</li>
  </ol>
</nav>
{% endblock %}
{% block students %}
    {% if course_name %}
        <nav class="navbar">
            <h2>{{ course_name }}</h2>
        </nav>
        <hr>
        <br>
        <div class="course_main" style="padding-left: 90px">
            <a href="#" style="color: black"><h5><img src="{% static 'images\folder.png' %}" width="17px" style="padding-bottom: 4px"> Materials</h5></a>
            <a href="{% url 'dl:for_attendance' course_id %}" style="color: black"><h5><img src="{% static 'images\group 1.png' %}" width="17px" style="padding-bottom: 4px"> Attendance</h5></a>
            <a href="#" style="color: black"><h5><img src="{% static 'images\marking 1.png' %}" width="17px" style="padding-bottom: 4px"> RK-1</h5></a>
            <a href="#" style="color: black"><h5><img src="{% static 'images\marking 1.png' %}" width="17px" style="padding-bottom: 4px"> RK-2</h5></a>
            <a href="#" style="color: black"><h5 class="select2-container--disabled"><img src="{% static 'images\verified-text-paper 1.png' %}" width="17px" style="padding-bottom: 4px"> Final Test</h5></a>
        </div>
        <br>
        {% for i in weeks %}
            <hr>
            <h4 style="padding-left: 20px;text-align: left">{{ forloop.counter }}-Week</h4>
            {% for t in tasks_list %}
                {% if forloop.parentloop.counter == t.week %}
                    {% if request.user.student.group in t.groups.all and date|date:"c" >= t.date1|date:"c" and date|date:"c" <= t.date2|date:"c"%}
                        <h5 style="padding-left: 70px"><img src="{% static 'images/list.png' %} " style="padding-bottom: 3px" width="20px"><a style="color: black" href="{% url 'dl:show_task' course_id t.pk %}"> {{ t.title }}</a></h5>
                    {% else %}
                        <h5 style="padding-left: 70px"><img src="{% static 'images/list.png' %} " style="padding-bottom: 3px" width="20px"><a class="disabled" style="pointer-events: none;color: dimgray" href="{% url 'dl:show_task' course_id t.pk %}"> {{ t.title }}</a></h5>
                        <span class="badge badge-pill badge-danger" style="margin-left: 100px">Restricted</span>
                        <ul>
                        {% if not request.user.student.group in t.groups.all %}
                            {% for gr in tasks_list %}
                            {% if not request.user.student.group in gr.groups.all %}
                              {% for group in gr.groups.all %}
                                <li style="margin-left: 105px">You belong to <strong>{{ group }}</strong></li>
                              {% endfor %}
                            {% endif %}

                            {% endfor %}
                            {% if not date|date:"c" >= t.date1|date:"c" and date|date:"c" <= t.date2|date:"c" %}
                                    <li style="margin-left: 105px">From: <strong>{{ t.date1|date:"SHORT_DATE_FORMAT" }} {{ t.date1|time:"G:i" }}</strong></li>
                                    <li style="margin-left: 105px">To: <strong>{{ t.date2|date:"SHORT_DATE_FORMAT" }} {{ t.date2|time:"G:i" }}</strong></li>
                            {% else %}
                                <li style="margin-left: 105px">From: <strong>{{ t.date1|date:"SHORT_DATE_FORMAT" }} {{ t.date1|time:"G:i" }}</strong></li>
                                    <li style="margin-left: 105px">To: <strong>{{ t.date2|date:"SHORT_DATE_FORMAT" }} {{ t.date2|time:"G:i" }}</strong></li>

                            {% endif %}
                            {% else %}
                            {% if not date|date:"c" >= t.date1|date:"c" and date|date:"c" <= t.date2|date:"c" %}
                                    <li style="margin-left: 105px">From: <strong>{{ t.date1|date:"SHORT_DATE_FORMAT" }} {{ t.date1|time:"G:i" }}</strong></li>
                                    <li style="margin-left: 105px">To: <strong>{{ t.date2|date:"SHORT_DATE_FORMAT" }} {{ t.date2|time:"G:i" }}</strong></li>
                            {% else %}
                                <li style="margin-left: 105px">From: <strong>{{ t.date1|date:"SHORT_DATE_FORMAT" }} {{ t.date1|time:"G:i" }}</strong></li>
                                    <li style="margin-left: 105px">To: <strong>{{ t.date2|date:"SHORT_DATE_FORMAT" }} {{ t.date2|time:"G:i" }}</strong></li>

                            {% endif %}
                            {% endif %}
                        </ul>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% for f in files_list %}
                {% if forloop.parentloop.counter == f.week %}
                    <h5 style="padding-left: 70px"><img src="{{ f.file.url|give_img }} " style="padding-bottom: 3px" width="20px"><a style="color: black" href="{{ f.file.url }}"> {{ f.title }}</a></h5>

                {% endif %}
                {% endfor %}
            {% endfor %}
    {% else %}
        error
    {% endif %}
{% endblock %}
{% block teachers %}
    {% if course_name %}
        <nav class="navbar">
            <h2>{{ course_name }}</h2>
        </nav>
        <hr>
        <br>
        <div class="course_main" style="padding-left: 90px">
            <a href="#" style="color: black"><h5><img src="{% static 'images\folders.png' %}" width="30px" style="padding-bottom: 4px"> Materials</h5></a>
            <a href="{% url 'dl:for_attendance' course_id %}" style="color: black"><h5><img src="{% static 'images\group.png' %}" width="30px" style="padding-bottom: 4px"> Attendance</h5></a>
            <a href="#" style="color: black"><h5><img src="{% static 'images\shopping-list.png' %}" width="30px" style="padding-bottom: 4px"> RK-1</h5></a>
            <a href="#" style="color: black"><h5><img src="{% static 'images\shopping-list.png' %}" width="30px" style="padding-bottom: 4px"> RK-2</h5></a>
            <a href="#" style="color: black"><h5 class="select2-container--disabled"><img src="{% static 'images\test.png' %}" width="30px" style="padding-bottom: 4px"> Final Test</h5></a>
            <a href="{% url 'dl:add_task_menu' course_id %}" style="color: black"><h5 class="select2-container--disabled"><img src="{% static 'images\clipboard.png' %}" width="30px" style="padding-bottom: 4px"> Add Task</h5></a>
        </div>
        <br>
        {% for i in weeks %}
            <hr>
            <h4 style="padding-left: 20px;text-align: left">{{ forloop.counter }}-Week<button class="huacamola" data-toggle="modal" data-target="#exampleModal" data-whatever="{{ forloop.counter }}"></button></h4>
            {% for t in tasks_list %}
                {% if forloop.parentloop.counter == t.week %}
                    <h5 style="padding-left: 70px"><img src="{% static 'images/list.png' %} " style="padding-bottom: 3px" width="20px"><a style="color: black" href="{% url 'dl:show_task' course_id t.pk %}"> {{ t.title }}</a></h5>
                {% endif %}
            {% endfor %}
            {% for f in files_list %}
                {% if forloop.parentloop.counter == f.week %}
                    <h5 style="padding-left: 70px"><img src="{{ f.file.url|give_img }} " style="padding-bottom: 3px" width="20px"><a style="color: black" href="{{ f.file.url }}"> {{ f.title }}</a></h5>

                {% endif %}
                {% endfor %}
            <form action="{% url 'dl:upload_file' course_id user.teacher.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Upload File</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="form-group">
                      <label for="recipient-name" class="col-form-label">Week:</label>
                      <input name="week" type="number" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                      <label for="message-text" class="col-form-label">Title:</label>
                        <input name="title" type="text" class="form-control" id="recipient-name">
                        <br>
                        <br>
                        <div class="input-group">
                     <div class="input-group-prepend">
                           <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                         </div>
                         <div class="custom-file">
                           <input type="file" class="custom-file-input" id="inputGroupFile01"
                             aria-describedby="inputGroupFileAddon01" name="file">
                           <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                             <h6></h6>
                         </div>
                        </div>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </div>
                </div>
              </div>
            </div>
            </form>
        {% endfor %}
    {% else %}
        errordwadwa
    {% endif %}
{% endblock %}

dl/templates/login.html
{% extends 'main.html' %}
{% block login %}
    <form action="{% url 'dl:check_account'%}" method="POST">
    {% csrf_token %}
      <div class="form-group">
        <label>Login:</label>
        <input name="enter_login" type="text" class="form-control" id="enter_login" placeholder="login...">
      </div>
      <div class="form-group">
        <label>Password</label>
        <input name="enter_pass" type="password" class="form-control" id="enter_pass" placeholder="password...">
      </div>
        {% if login_error %}
            <label style="color: red">{{ login_error }}</label>
        {% endif %}
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Remember me</label>
      </div>
    <button type="submit" class="btn btn-outline-dark">Log In</button>
    </form>
{% endblock %}
{# Load the tag library #}

dl/templates/rate.html
{% extends 'main.html' %}
{% block title %}Rate{% endblock %}
{% load cmds %}
{% block navigation %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'dl:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'dl:courses' course_id %}">{{ course_name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'dl:show_task' course_id task.pk %}">{{ task.title }}</a></li>
    <li class="breadcrumb-item disabled" >{{ group_name}}</li>
    <li class="breadcrumb-item" aria-current="page">Rate</li>
  </ol>
</nav>
{% endblock %}
{% block teachers %}
    <nav class="navbar">
            <h2>{{ task.title }}</h2>
        </nav>
    <hr>
    <table class="table table-striped table-light table-borderless table-hover table-hover-cells">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Student</th>
            <th scope="col">Grade</th>
            <th scope="col">Uploaded File</th>
            <th scope="col">Option</th>
        </tr>
        </thead><tbody>
        {% for s in students_list %}
        <form action="{% url 'dl:set_grade' course_id s.group_id user.pk s.pk task.pk %}" method="POST">
            {% csrf_token %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <th><h6><a href="{% url 'dl:see_profile' s.user.pk %}" style="color: black">({{ s.user.username }}) {{ s.user.first_name }} {{ s.user.last_name }}</a></h6></th>
                <th>


                            <input  type="number" style="height: 30px; width: 75px" class="form-control" name="inputGrade" placeholder="0"
                                   {% for g in grades_list %}
                                       {% if s.pk == g.student_id %}
                                        value="{{ g.grade }}"
                                    {% endif %}
                                   {% endfor %}
                            >


                </th>
                <th>
                    {% for f in files_list %}
                        {% if f.student == s.user.student %}<h5 ><img src="{{ f.file.url|give_img }} " style="padding-bottom: 3px" width="20px"><a style="color: black" href="{{ f.file.url }}"> {{ f.file.name }}</a></h5>{% endif %}
                 {% endfor %}
                </th>
                <th><button type="submit" class="btn btn-dark btn-sm" >Save</button></th>
            </tr>

            </form>
        {% endfor %}</tbody>
    </table>
{% endblock %}